### ISSUE TITLE
[Smart Item] string concatenation makes source of GLTFShape not showing

### ISSUE THREAD

**Issue by pabloes** [decentraland/issues#20]
on spawn method:
```
      const num = 1;
      const shape = new GLTFShape(`models/fish${num}.glb`); // DOES NOT WORK
      //const shape = new GLTFShape(`models/fish1.glb`); //WORKS
```

Used here string template, butiIt fails with any kind of string concatenation.

Example here: https://github.com/pabloes/report-smart-item-glb-string/blob/main/src/item.ts

**Comment by cazala** [comment]
Hi pablo, yes this is a known constrain, it is due to the way the mappings are generated: mappings are what translates local paths like `models/fish1.glb` into IPFS hashes like `QmbV4zmkLFpL8DRzppr5oUqYn7fcPb8pqktYKt3vkVbyg1`. Template strings result in error when namespacing and generating the mappings. The workaround for now is to have several constants for those paths, and use those when needed instead of template strings. If you need help with this you can hit me up on discord or slack.

**Comment by pabloes** [comment]
Thx for the explanation, I already applied the workaround. I guess we can close the issue and have it as reference.
