### ISSUE TITLE
several bugs

### ISSUE THREAD

**Issue by CryptoWorldGames** [decentraland/issues#510]
### What happened?

this is my first time in decentraland and its not a good experience.
1. the controls are too sloppy. i barely move my mouse and the view wants to swing around way way way too fast.
2. the music is stupid and too loud, i went to settings, changed music to 0 and hit esc and it was still loud. finally after running outside the building it got quiet.
3. i noticed my name was supposed to be CryptoWorld but its CryptoWorld#ea43
4. i went to my profile to change my name and it appeared to work, but there is no save button and it would never save. i was trying to delete the #ea43 showing at the end. i even hit space bar 5 times and it showed my number of characters of my username went from 11 to 15 and still didnt see a way to save it, i hit esc and it didnt save. 
5. it asks to type something about me so i did, said i'm owner of cryptoworldgames.com and it wouldnt save it. there is no save button. clicking anywhere on the screen didnt work, hitting escape didnt work.
6. you wanted me to sign in to my wallet so i chose metamask and it wanted eth and not bep20. 
are you kidding me? with the eth fees as high as they are why would you build this on the stupid eth network?

make it available for bep20, xinfin, and tron networks o m g

i'm a freaking webmaster and i didnt know how to do this and had this much trouble? how will others play this if i have this much trouble

### Steps to reproduce

this is my first time in decentraland and its not a good experience.
1. the controls are too sloppy. i barely move my mouse and the view wants to swing around way way way too fast.
2. the music is stupid and too loud, i went to settings, changed music to 0 and hit esc and it was still loud. finally after running outside the building it got quiet.
3. i noticed my name was supposed to be CryptoWorld but its CryptoWorld#ea43
4. i went to my profile to change my name and it appeared to work, but there is no save button and it would never save. i was trying to delete the #ea43 showing at the end. i even hit space bar 5 times and it showed my number of characters of my username went from 11 to 15 and still didnt see a way to save it, i hit esc and it didnt save. 
5. it asks to type something about me so i did, said i'm owner of cryptoworldgames.com and it wouldnt save it. there is no save button. clicking anywhere on the screen didnt work, hitting escape didnt work.
6. you wanted me to sign in to my wallet so i chose metamask and it wanted eth and not bep20. 
are you kidding me? with the eth fees as high as they are why would you build this on the stupid eth network?

make it available for bep20, xinfin, and tron networks o m g

i'm a freaking webmaster and i didnt know how to do this and had this much trouble? how will others play this if i have this much trouble

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63 LikeWise/90  windows 10.6.3395.96

### Wallet

Metamask

### CPU

desktop-jpggrne dell inspiron 5680

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

15.9

### Kernel Version

1.0.0-2949092612.commit-101f737

### Unity Version

1.0.51023-20220825223709.commit-4ddec93

### Realm

artemis

### NameTag

CryptoWorld#ea43

**Comment by kwspgoliasz** [comment]
Hello, thank you for contacting us. We're sorry for the issues you've encountered while using Decentraland. I'll address your queries one by one.
1) Thank you for bringing this to our attention. We appreciate the feedback regarding the controls and we will look into any possibilities of improving them in the future.
2) The music in the background is sometimes considered a part of the world SFX. If changing the Music option does not help, please try to reduce the volume of the World SFX option instead.
3) The random symbols after the username are added to every Decentraland avatar. Unfortunately it is not possible to remove them. In order to have a username without these symbols, it would be required to claim a unique name which no one else is already using. This can be done in the Decentraland's Builder section found on our website: https://decentraland.org/.
4) The issues described in points 4 and 5 are already reported and the developers are doing their best to deal with them as soon as possible. It might take some time but please keep an eye out for further updates to the platform. We're truly sorry for the inconvenience.
5) Unfortunately, at the moment only ETH can be used in Decentraland. I will provide your feedback to the relevant team so they can discuss this issue in more depth.

In case of any further questions, do not hesitate to contact us again.

**Comment by CryptoWorldGames** [comment]
You need to use cnr from centric.com its a rise only token. So
decentralized will get rich just by holding it as main crypto
