### ISSUE TITLE
genesis Plaza 2nd floor's lift doesnt work

### ISSUE THREAD

**Issue by xemixemi** [decentraland/issues#517]
### What happened?

I jumped into de waterhole inmediatelly after entering the guest session. After talking to the octopus guy at the bottom floor i jumped into the lift to the intermediate floor and i got stucked there because i wasnt able to make goup any of the 2 lifts there.

### Steps to reproduce

1- enter genesis plaza
2 - dive into the waterhole
3- talk to the ocotpus at bottom floor
4- jump into lift to the next floor (atari machines / billiard table one)
5- jump into any of the 2 available lifts. nothing happens.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

None, played as guest

### CPU

Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

### GPU

NVIDIA GeForce GTX 860M 2010MB

### RAM

16303MB

### Kernel Version

1.0.0-3002225086.commit-aca9674

### Unity Version

desktop-1.0.572-20220902135606.commit-6c11e72

### Realm

dg

### NameTag

WeonCuliao#2c13

**Comment by kwspgoliasz** [comment]
Thank you for reporting the issue to us. The ticket will be forwarded to the relevant team, in order for us to investigate the issue.

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. The issue you reported to us is currently being investigated in a separate ticket. Due to that reason, this ticket will be closed. All of the details and updates regarding this issue can be found in the ticket: [#2984](https://github.com/decentraland/unity-renderer/issues/2984). 
In case of any problems, please do not hesitate to contact us again.
