### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by caticon88** [decentraland/issues#521]
### What happened?

tables are not visible at the location ice pocker 

### Steps to reproduce

-

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz

### GPU

NVIDIA GeForce GTX 1650 with Max-Q Design 3962MB

### RAM

8010MB

### Kernel Version

1.0.0-3070111756.commit-6bf4b93

### Unity Version

desktop-1.0.580-20220912223148.commit-52c962e

### Realm

baldr

### NameTag

Caticon#8ed3

**Comment by kwspgoliasz** [comment]
Hello, thank you for bringing this issue to our attention. Unfortunately, we were unable to reproduce it on our side.
If possible, could you check if the issue still occurs after exiting your wallet and then logging in to the platform with it again?
If the problem will persist, please provide us with a screenshot, or a video showing the issue.

Additionally, the Ice Poker may sometimes by blocked if the platform was accessed via a VPN. If possible, please let us know if one was used when the issue occurred.

**Comment by caticon88** [comment]
https://user-images.githubusercontent.com/113771554/191804182-4c94e709-b7cd-43d2-803e-c8bbc63c44ab.mp4
Vpn is not used. Logged in as a guest, without wallet. No change

Another error. Location wilderness p2e - bounty hunter
https://user-images.githubusercontent.com/113771554/191809157-3a44a604-165a-4cb2-978d-f4c0e117fbac.mp4
Can't move from place

**Comment by caticon88** [comment]
https://user-images.githubusercontent.com/113771554/193040188-298a4ce8-d04f-4405-95fe-0bfe501430ab.mp4

Tominoya - empty

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We managed to reproduce the issue on our side. The relevant team is investigating the problem in order to fix it as soon as possible. As a separate ticket was created for this issue, this ticket will be closed. All of the details and updates can be found in ticket [#3137](https://github.com/decentraland/unity-renderer/issues/3137). 
In case of any other problems, please do not hesitate to contact us.
