### ISSUE TITLE
load game

### ISSUE THREAD

**Issue by benyamiiiin** [decentraland/issues#522]
### What happened?

hi . the game dont show me the tables and the frogs and leaderboard . icant start playing . itryed with site and beta . what should i do for playing ?

### Steps to reproduce

the game dont show me the tables and the frogs and leaderboard . icant start playing . itryed with site and beta . what should i do for playing ?

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 5500U with Radeon Graphics 

### GPU

AMD Radeon(TM) Graphics 3752MB

### RAM

7504MB

### Kernel Version

1.0.0-3070111756.commit-6bf4b93

### Unity Version

desktop-1.0.607-20220919211048.commit-5665405

### Realm

dg

### NameTag

benyamiiiin#3c2d

**Comment by kwspgoliasz** [comment]
Hello, thank you for bringing this issue to our attention. I understand that you have some issue with the Ice Poker scene. Unfortunately, we were unable to reproduce it on our side.
If possible, could you check if the issue still occurs after exiting your wallet and then logging in to the platform with it again?
If the problem will persist, please provide us with a screenshot, or a video showing the issue.

Additionally, the Ice Poker may sometimes by blocked if the platform was accessed via a VPN. If possible, please let us know if one was used when the issue occurred.

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We managed to reproduce the issue on our side. The relevant team is investigating the problem in order to fix it as soon as possible. As a separate ticket was created for this issue, this ticket will be closed. All of the details and updates can be found in ticket https://github.com/decentraland/unity-renderer/issues/3137.
In case of any other problems, please do not hesitate to contact us.
