### ISSUE TITLE
HUD not loading - cant play

### ISSUE THREAD

**Issue by Alcyd** [decentraland/issues#525]
### What happened?

only players are being loaded when logging in, none of the tables or HUD informations isnt

### Steps to reproduce

login

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2400G with Radeon Vega Graphics 

### GPU

NVIDIA GeForce GTX 1050 Ti 4018MB

### RAM

16331MB

### Kernel Version

1.0.0-3106729404.commit-4698e1d

### Unity Version

desktop-1.0.610-20220922161204.commit-08403ae

### Realm

dg

### NameTag

Alcyd#8ff8

**Comment by Alcyd** [comment]
Any update on this?

**Comment by Alcyd** [comment]
I am unable to play, would appreciate any help NOW.

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We managed to reproduce the issue on our side. The relevant team is investigating the problem in order to fix it as soon as possible. As a separate ticket was created for this issue, this ticket will be closed. All of the details and updates can be found in ticket [#3137](https://github.com/decentraland/unity-renderer/issues/3137). 
In case of any other problems, please do not hesitate to contact us.

**Comment by nelonelo** [comment]
Hi , I have the same problem , Tried everything for the last 2 weeks. Can you help me to please.
