### ISSUE TITLE
iceproblem

### ISSUE THREAD

**Issue by dusho33231** [decentraland/issues#527]
### What happened?

When I start the game and go to icepoker it doesn't load the tables missions and chips please help me

### Steps to reproduce

When I start the game and go to icepoker it doesn't load the tables missions and chips please help me
![problem icepoker](https://user-images.githubusercontent.com/114305943/192110145-6bbd5a1f-5f7e-4f82-82a5-7727280907ef.PNG)

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

### GPU

NVIDIA GeForce GTX 1050 1977MB

### RAM

8157MB

### Kernel Version

1.0.0-3106729404.commit-4698e1d

### Unity Version

desktop-1.0.614-20220923172652.commit-85e7e67

### Realm

baldr

### NameTag

Dusho28#eae9

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We managed to reproduce the issue on our side. The relevant team is investigating the problem in order to fix it as soon as possible. As a separate ticket was created for this issue, this ticket will be closed. All of the details and updates can be found in ticket [#3137](https://github.com/decentraland/unity-renderer/issues/3137). 
In case of any other problems, please do not hesitate to contact us.
