### ISSUE TITLE
Problems loading "Ice Poker The Strong Hold"

### ISSUE THREAD

**Issue by jmoyano90** [decentraland/issues#530]
### What happened?

several days ago I entered "Ice Poker The Strong Hold", and the tables do not load, I have already tried several ways, including uninstalling and reinstalling the "Decentralanda desktop", this seems strange to me since the times that I something similar happened, it was solved by reloading or reinstalling, it had never happened to me that this situation lasted more than a day, it has been 4 days so far.
https://imgur.com/a/bmJcQVo

### Steps to reproduce

I didn't know how to guide you with the solution, but maybe restarting the Decentraland Games servers can solve the problem.

### Operating System

Windows 10  (10.0.19042) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3400G with Radeon Vega Graphics 

### GPU

AMD Radeon(TM) RX Vega 11 Graphics 7133MB

### RAM

14267MB

### Kernel Version

1.0.0-3127331658.commit-879a231

### Unity Version

desktop-1.0.614-20220923172652.commit-85e7e67

### Realm

dg

### NameTag

javo#e253

**Comment by kwspgoliasz** [comment]
Hi, thank you for your patience. We managed to reproduce the issue on our side. The relevant team is investigating the problem in order to fix it as soon as possible. As a separate ticket was created for this issue, this ticket will be closed. All of the details and updates can be found in ticket [#3137](https://github.com/decentraland/unity-renderer/issues/3137). 
In case of any other problems, please do not hesitate to contact us.
