### ISSUE TITLE
Windowed Resolution Scaling Issue

### ISSUE THREAD

**Issue by diversivegamer** [decentraland/issues#537]
### What happened?

I have the resolution set to windowed 1600x900 16:9 and every time I close then relaunch the client no matter how short or long between the resolution changes and I must go back into settings and fix every time. I have graphics quality set to Epic.

![Set](https://user-images.githubusercontent.com/78673432/196368411-7e576026-5b73-463c-abe5-8274abf9b9e6.png)
![Relaunched](https://user-images.githubusercontent.com/78673432/196368431-0618d3b2-a9f0-4b7f-b48a-730f428e3d45.png)

### Steps to reproduce

Launch client and log in, set client to windowed mode, set resolution to 1600x900(set graphics quality to EPIC if necessary), leave settings menu, exit client completely, relaunch.

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 3600 6-Core Processor 

### GPU

NVIDIA GeForce GTX 1660 5991MB

### RAM

32714MB

### Kernel Version

1.0.0-3268540295.commit-9e5f098

### Unity Version

desktop-1.0.648-20221013174545.commit-75db7ad

### Realm

baldr

### NameTag

DiversiveGamer

**Comment by diversivegamer** [comment]
Sorry forgot to mention when relaunched the drop down menu will still show its 1600x900 though the window and UI are both clearly not scaled properly. Also ULTRA not epic.

**Comment by kwspgoliasz** [comment]
Hi, thank you for contacting us. This issue was already brought to our attention in another ticket. The relevant team will look into it as soon possible.
As all of the updates are going to be provided in the ticket [#2885](https://github.com/decentraland/unity-renderer/issues/2885), this ticket will be closed.
Please, don't hesitate to contact us again in case of any questions.
