### ISSUE TITLE
cant get the quest reward 

### ISSUE THREAD

**Issue by PedarPadesha** [decentraland/issues#55]
### What happened?

unable to get the reward when i get done with the quest. API error 

### Steps to reproduce

quest mission error 

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.38

### Wallet

Metamask

### CPU

ryzen 9

### GPU

rtx 3060

### RAM

32gb

### Kernel Version

1.0.0-1399994176.commit-9bd8e36

### Unity Version

1.0.18188-20211030153253.commit-2d4df83

### Realm

hephaestus

### NameTag

Padesha#c650

**Comment by nearnshaw** [comment]
Hi!

If this issue is regarding the DappCraft SteamPunk quest, this issue has now been resolved, thanks for reporting. If the issue was regarding a different quest, please reopen and provide more detail.

If you enter the scene with the same account you originally used, you should now be able to talk to the NPC to complete the final step, and this time you'll receive the reward for completing the quest.

https://play.decentraland.org/?position=38%2C12
