### ISSUE TITLE
NOT OPEN DECENTRALAND FOR WINDOWS WHIT METAMASK

### ISSUE THREAD

**Issue by paliveira** [decentraland/issues#550]
### What happened?

Since yesterday, when selecting the metamask for authentication, it opens the walletconnect connector, but it only occurs in the desktop version. This makes it impossible to use, having to use only the browser version.

### Steps to reproduce

every time I try to connect via desktop client.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

### Wallet

Metamask

### CPU

AMD FX(tm)-8320 Eight-Core Processor              3.50 GHz

### GPU

GPU Radeon RX550/550 Series Primário/Independente

### RAM

16GB

### Kernel Version

1.0.0-3346881156.commit-d4588f4

### Unity Version

1.0.60189-20221028142813.commit-7e54658

### Realm

baldr

### NameTag

Paliveira#71de

**Comment by kwspgoliasz** [comment]
Hello, thank you for contacting us.

This issue was already addressed in ticket [#394](https://github.com/decentraland/explorer-desktop/issues/394). This behaviour is expected for the metamask login on the desktop client, as the walletconnect connector is used for the metamask accounts as well. Scanning the created QR code with your metamask app should allow you to log in with your metamask account as well.

Don't hesisate to contact us again in case of further issues.
