### ISSUE TITLE
Can't Get Rid of Spooky Girl Skin With Purple Hat Wearable

### ISSUE THREAD

**Issue by ImageComposer** [decentraland/issues#551]
### What happened?

It does not matter where I am on the map, I can not get rid of the spooky girl skin with purple hat wearable.  I change wearables, get rid of the spooky girl skin and click on "Done".  No changes are kept.   I tried many times and no changes kept.  I tried logging out of Decentraland and logging back in but this did not solve the issue.  Changing realms did not solve the issue.
![10-31-2022](https://user-images.githubusercontent.com/116951138/198998303-5782b8d7-c978-430c-a935-695d69f4c4aa.JPG)

### Steps to reproduce

Select any wearables to remove spooky girl skin with purple hat wearable.  Click "Done".  Changes you make will not be kept and avatar goes back to spooky girl skin with purple hat wearable.

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Intel i9 10th generation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32 GB

### Kernel Version

1.0.0-3346881156.commit-d4588f4

### Unity Version

1.0.60189-20221028142813.commit-7e54658

### Realm

baldr

### NameTag

Petunia#a039

**Comment by kwspgoliasz** [comment]
HI, thank you for bringing this issue to our attention.

The relevant team is already aware of the problem and is doing their best to deal with it as soon as possible. As the issue is already reported, this ticket will be closed. You can find the latest updates for the issue in the following ticket: [#3379](https://github.com/decentraland/unity-renderer/issues/3379).
