### ISSUE TITLE
Game Crash/ Memory Allocation | Runtime Error

### ISSUE THREAD

**Issue by acrosscoder** [decentraland/issues#560]
### What happened?

Issues
* The platform loads objects slowly and  crashed when loaded in crowded places
* Shows this 
![image](https://user-images.githubusercontent.com/39716656/201436553-eba9d5b7-b65c-463c-a6f0-4f19a92151e0.png)

### Steps to reproduce

Try loading an avatar on crowded locations

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

16GB

### Kernel Version

1.0.0-3447314206.commit-3cd6272

### Unity Version

1.0.62009-20221110094428.commit-e193250

### Realm

artemis

### NameTag

JimSedric

**Comment by acrosscoder** [comment]
![image](https://user-images.githubusercontent.com/39716656/201482821-cfee2d1f-b88d-403c-85de-02b0dcc7fbdd.png)

**Comment by kwspgoliasz** [comment]
Hi, thank you for reaching out to us. We sorry for the troubles caused by this issue. Due to the memory allocation limits, the platform may sometimes crash in this manner. The issue tends to occur during prolonged sessions, in extremely crowded places or scenes causing heavy load for the platform. We are aware of the issue, but for now there is no specific ETA for any fixes.
If you encounter any other issues or crashes, please don't hesitate to contact us again.
