### ISSUE TITLE
Ação travada

### ISSUE THREAD

**Issue by GayaSource** [decentraland/issues#567]
### What happened?

A torre do Vip Tower Coming Som não abre para realizar a missões

### Steps to reproduce

A mesa de missões, não abre a torre. Se for pessoalmente até a torre o ellevador também não abre

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

### GPU

Intel(R) UHD Graphics 3990MB

### RAM

7981MB

### Kernel Version

2.0.0-3518367822.commit-2ad26e6

### Unity Version

desktop-1.0.805-20221116144427.commit-ad3486c

### Realm

dg

### NameTag

Gaya#e274

**Comment by kwspgoliasz** [comment]
Hi, thank you for contacting us. This seems to be a problem with the scene SDK implementation. If you're still experiencing the issue, please create another ticket for it in English. The ticket should include coordinates for the broken scene and a screenshot/video showing the issue. Additionally, you could try contacting the scene creator in order to fix the issue.
