### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GayaSource** [decentraland/issues#568]
### What happened?

Elevador do Shop sobe e deixa o avatar preso no espaço 

### Steps to reproduce

Saindo do terreo para o 3 andar. 

### Operating System

Windows 11  (10.0.22000) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

### GPU

Intel(R) UHD Graphics 3990MB

### RAM

7981MB

### Kernel Version

2.0.0-3518367822.commit-2ad26e6

### Unity Version

desktop-1.0.805-20221116144427.commit-ad3486c

### Realm

dg

### NameTag

Gaya#e274

**Comment by kwspgoliasz** [comment]
Hi, thank you for contacting us. This seems to be a problem with the scene SDK implementation. If you're still experiencing the issue, please create another ticket for it in English. The ticket should include coordinates for the broken scene and a screenshot/video showing the issue. Additionally, you could try contacting the scene creator in order to fix the issue.
