### ISSUE TITLE
Guardar pasos

### ISSUE THREAD

**Issue by Aaxeel** [decentraland/issues#573]
### What happened?

Por ejemplo, acabo de hacer las primeras 20 misiones y encontrar los 10 balones y al cambiar de parcela y volver no se me ha guardado, me marca que lo tengo que volver a hacer

### Steps to reproduce

...

### Operating System

Windows 10  (10.0.19044) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz

### GPU

NVIDIA GeForce GTX 1660 SUPER 5991MB

### RAM

16319MB

### Kernel Version

2.0.0-3620238961.commit-0fb0a45

### Unity Version

desktop-1.0.866-20221202211207.commit-cd84718

### Realm

baldr

### NameTag

Aaxeel#a2fa

**Comment by kwspgoliasz** [comment]
Hello, thank you for reaching out to us. Could you provide us with some additional information, so that we can thoroughly investigate the issue?
We'd like to ask for specific coordinates of the location where the issue occurs. It would also be very helpful if you could send us a screenshot, or a video of the issue.
Additionally, we'd like to request for the conversation to be held in English from now on.

**Comment by pabloes** [comment]
I think it's something related with LaLiga land missions. Probably the developer is not maintaining the user mission state in a backend.
https://twitter.com/LaLigaLand

**Comment by kwspgoliasz** [comment]
An issue with specific scene would be related to the scene SDK implementation, not to Decentraland's client. You could try contacting the scene creator in order to fix the issue.
