### ISSUE TITLE
Videos not working in CBI bulding.

### ISSUE THREAD

**Issue by littlefoott** [decentraland/issues#578]
### What happened?

video screen is blank and nothing plays when I click it as instructed.

### Steps to reproduce

look at video screen in CBI building

### Operating System

Windows 10  (10.0.19045) 64bit

### Wallet

Metamask

### CPU

AMD Ryzen 5 2400G with Radeon Vega Graphics 

### GPU

Radeon RX550/550 Series 2027MB

### RAM

14249MB

### Kernel Version

2.0.0-3706422264.commit-09c79d4

### Unity Version

desktop-1.0.954-20221215145051.commit-bd41e54

### Realm

dg

### NameTag

Lovvr#3c60

**Comment by kwspgoliasz** [comment]
Thank you for reaching out to us. Lately we had some issues with videos on the desktop client, but they should have already been fixed. Could you try clearing you desktop client data, or reinstalling the client, and then check whether the videos for the CBI building are still broken? If the issue keeps occurring, please provide us with a video of the issue so that we can investigate the matter in detail.

**Comment by kwspgoliasz** [comment]
Closing this issue due to lack of response for two weeks. Don't hesitate to contact us again in case of any other questions.
