### ISSUE TITLE
Bug mining wonderzone

### ISSUE THREAD

**Issue by victop75** [decentraland/issues#597]
### What happened?

I can't mine anymore ! And it's not because my axe need repair. it displays a very strange screen, indicating i'm back to level 1, with 0 gold and 0 gems, and I can't mine nor repair my axe, it's really strange, have you ban my account from mining ?
![decentraland bug](https://user-images.githubusercontent.com/78036980/216407099-16b7a932-3dc2-4505-a17c-b061a4a80d79.png)

### Steps to reproduce

Just modify this bug asap please

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70

### Wallet

Metamask

### CPU

intel i9 10th generation

### GPU

ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.76005-20230202020608.commit-59dde07

### Unity Version

1.0.76005-20230202020608.commit-59dde07

### Realm

unicorn

### NameTag

#b5f3

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. Unfortunately we have been unable to reproduce the issue on our side. This appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. If the issue will continue to occur for you please try contacting the scene creator in order to fix the issue.
