### ISSUE TITLE
WONDERMINE ITEMS ALL GONE!

### ISSUE THREAD

**Issue by NAMBAY** [decentraland/issues#598]
### What happened?

I loggeed on today to do my daily wondermine collecting, and i finished, then the game got laggy and i logged off, and when i got back on, mmy coins where at 0, my everything! ZERO!
there is no pickaxe in my pickaxe window and I was close to the second to last pick! now it says hwen i hover over the pickaxe slot, "CrescentLavaPickaxe #333
Remaining: 400"

PLEASE HELP AND GET MY STUFF BACK!

### Steps to reproduce

Give me my stuff back in wondermine

### Operating System

Windows 11  (10.0.22621) 64bit

### Wallet

Metamask

### CPU

Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

### GPU

NVIDIA GeForce GTX 1070 with Max-Q Design 8082MB

### RAM

32617MB

### Kernel Version

1.0.76752-20230203162933.commit-b61b534

### Unity Version

1.0.76752-20230203162933.commit-b61b534

### Realm

heimdallr

### NameTag

e5b#7255

**Comment by kwssbocian** [comment]
Hello and thank you for bringing this issue to our attention. Unfortunately we have been unable to reproduce the issue on our side. This appears to be a problem with the scene SDK implementation, not with Decentraland's client itself. If the issue will continue to occur for you please try contacting the scene creator in order to fix the issue.
